
services:
  # PostgreSQL
  pgdb:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app_network

  # Redis
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network

  # backend_rds
  backend_rds:
    image: 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_rds:latest
    environment:
      DB_HOST: pgdb
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: admin
      DB_NAME: postgres
      CORS_ALLOWED_ORIGINS: "http://localhost:8081"
    ports:
      - "8081:8000"
    depends_on:
      - pgdb
      - redis
    networks:
      - app_network

  # backend_redis
  backend_redis:
    image: 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_redis:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CORS_ALLOWED_ORIGINS: "http://localhost:8082"
    ports:
      - "8082:8000"
    depends_on:
      - redis
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  pgdb:
    driver: local