name: Backend RDS CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend_rds/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 575108927078.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image for backend_rds
        run: |
          docker build -t backend_rds-image ./backend_rds

      - name: Push Docker image to AWS ECR
        run: |
          docker tag backend_rds-image:latest 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_rds:latest
          docker push 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_rds:latest
          
          # Деплой на EC2
      - name: Deploy to EC2 (backend_rds)
        run: |
            ssh -i "your-key.pem" ec2-user@${{ secrets.EC2_HOST }} \
                'docker pull 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_rds:latest && \
                docker run -d -p 8081:8000 f1-store-backend_rds:latest'
        env:
              PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
              HOST: ${{ secrets.EC2_HOST }}

