name: Backend RDS CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend_rds/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонування коду
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Налаштування AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # Крок 3: Деплой на EC2 (Backend Redis)
      - name: Deploy to EC2 (backend_redis)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/your-key.pem
          chmod 600 ~/.ssh/your-key.pem
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/your-key.pem ec2-user@${{ secrets.EC2_HOST }} \
            'cd /path/to/your/app && docker-compose pull && docker-compose up -d'
        env:
          HOST: ${{ secrets.EC2_HOST }}
