name: Backend RDS CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend_rds/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонування коду
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Налаштування AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      # Крок 3: Логін до AWS ECR
      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 575108927078.dkr.ecr.us-east-1.amazonaws.com

