name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Пайплайн спрацьовує на push до гілки main
  pull_request:
    branches:
      - main  # Пайплайн також спрацьовує на pull request до гілки main

jobs:
  build:
    runs-on: ubuntu-latest  # Виконуватиметься на останній версії Ubuntu

    steps:
      # Крок 1: Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v2  # Клонує код з репозиторію

      # Крок 2: Налаштування Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Налаштовує Docker Buildx для багатоплатформових образів

      # Крок 3: Логін до DockerHub (якщо використовуєш DockerHub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username з GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub password з GitHub Secrets

      # Крок 4: Будуємо Docker образ і пушимо його в Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .  # Створення Docker образу
          docker push your-image-name  # Завантаження Docker образу в Docker Hub

      # Крок 5: Запуск тестів у Docker контейнері
      - name: Run tests
        run: |
          docker run --rm your-image-name pytest  # Запуск тестів в контейнері

      # Крок 6: Деплой на сервер EC2
      - name: Deploy to AWS EC2
        run: |
          ssh -i "your-key.pem" user@ec2-instance-ip 'docker pull your-image-name && docker-compose up -d'
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}  # Приватний ключ для доступу до EC2
          HOST: ${{ secrets.EC2_HOST }}  # IP або домен EC2
