name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Виконуватиметься на останній версії Ubuntu

    steps:
      # Крок 1: Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Налаштування Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Крок 3: Налаштування AWS облікових даних
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Крок 4: Логін до AWS ECR
      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 575108927078.dkr.ecr.us-east-1.amazonaws.com

      # Крок 5: Логін до Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Кроки для кожного Docker образу
      - name: Build backend_rds Docker image
        run: |
          docker build -t backend_rds-image -f ./backend_rds/Dockerfile ./backend_rds

      - name: Build backend_redis Docker image
        run: |
          docker build -t backend_redis-image -f ./backend_redis/Dockerfile ./backend_redis

      - name: Build frontend Docker image
        run: |
          docker build -t frontend-image -f ./frontend/Dockerfile ./frontend

      # Крок 6: Пуш Docker образи в Docker Hub
      - name: Push Docker images to Docker Hub
        run: |
          docker push backend_rds-image
          docker push backend_redis-image
          docker push frontend-image

      # Крок 7: Пуш Docker образи в AWS ECR
      - name: Push Docker images to AWS ECR
        run: |
          docker tag backend_rds-image:latest 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_rds:latest
          docker tag backend_redis-image:latest 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_redis:latest
          docker push 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_rds:latest
          docker push 575108927078.dkr.ecr.us-east-1.amazonaws.com/f1-store-backend_redis:latest

      # Кроки для тестів
      - name: Run backend_rds tests
        run: |
          docker run --rm backend_rds-image pytest

      - name: Run backend_redis tests
        run: |
          docker run --rm backend_redis-image pytest

      - name: Run frontend tests
        run: |
          docker run --rm frontend-image pytest

      # Деплой на EC2
      - name: Deploy to AWS EC2
        run: |
          ssh -i "your-key.pem" user@ec2-instance-ip 'docker pull frontend-image && docker-compose up -d'
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}

      # Крок 11: Збереження змінної для подальшого використання
      - name: Set environment variable for future steps
        run: |
          echo "MY_ENV_VARIABLE=some_value" >> $GITHUB_ENV

      # Крок 12: Використання збереженої змінної середовища
      - name: Use environment variable
        run: |
          echo "The value is $MY_ENV_VARIABLE"
