name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'  # Відслідковуємо зміни тільки у frontend
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'  # Відслідковуємо зміни при PR для frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image for frontend
        run: |
          docker build -t frontend-image ./src/frontend

      - name: Deploy frontend to S3
        run: |
          aws s3 sync ./src/frontend s3://your-s3-bucket-name
